### ISSUE TITLE
Magento 2.4.4 / PHP 8.1 compatibility

### ISSUE THREAD

**Issue by claudio-ferraro** [indykoning/cli-helpers#8]
Since Magento 2.4.4 PHP 8.1 is used, however the cli-helpers package is not yet compatible with it.

For example when running the command: `cli-helpers db-magerun` the following error message appears:

```bash /Users/{user}/.composer/vendor/indykoning/cli-helpers/mk/scripts/db-magerun.sh
Downloading database from remote and stripping '@2fa @aggregated @customers @idx @log @oauth @quotes @replica @sales @search @sessions @stripped @trade @temp'

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/magerun2/vendor/symfony/console/Helper/HelperSet.php on line 112

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Inline.php on line 49

Fatal error: Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php:532
Stack trace:
#0 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(532): abs('')
#1 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(258): Symfony\Component\Yaml\Parser->parseValue('>', false, false, false, 'mapping')
#2 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse('Sales data (ord...', false, false, false)
#3 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(151): Symfony\Component\Yaml\Parser->parseBlock(176, 'id: sales\ndescr...', false, false, false)
#4 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse('- id: admin\n  d...', false, false, false)
#5 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock(132, '- id: admin\n  d...', false, false, false)
#6 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse('table-groups:\n ...', false, false, false)
#7 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock(131, 'table-groups:\n ...', false, false, false)
#8 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(320): Symfony\Component\Yaml\Parser->doParse(Array, false, false, false)
#9 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(246): Symfony\Component\Yaml\Parser->parseBlock(46, 'customCommands:...', false, false, false)
#10 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php(78): Symfony\Component\Yaml\Parser->doParse(Array, false, false, false)
#11 phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Yaml.php(64): Symfony\Component\Yaml\Parser->parse('application:\n  ...', false, false, false)
#12 phar:///usr/local/bin/magerun2/src/N98/Magento/Application/ConfigFile.php(93): Symfony\Component\Yaml\Yaml::parse('application:\n  ...')
#13 phar:///usr/local/bin/magerun2/src/N98/Magento/Application/ConfigurationLoader.php(162): N98\Magento\Application\ConfigFile->toArray()
#14 phar:///usr/local/bin/magerun2/src/N98/Magento/Application/ConfigurationLoader.php(112): N98\Magento\Application\ConfigurationLoader->loadDistConfig(Array)
#15 phar:///usr/local/bin/magerun2/src/N98/Magento/Application/Config.php(257): N98\Magento\Application\ConfigurationLoader->getPartialConfig(true)
#16 phar:///usr/local/bin/magerun2/src/N98/Magento/Application.php(380): N98\Magento\Application\Config->loadPartialConfig(true)
#17 phar:///usr/local/bin/magerun2/src/N98/Magento/Application.php(315): N98\Magento\Application->init(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /usr/local/bin/magerun2(8): N98\Magento\Application->run()
#19 {main}
  thrown in phar:///usr/local/bin/magerun2/vendor/symfony/yaml/Parser.php on line 532```

**Comment by indykoning** [comment]
I'm guessing this actually has to do with the version of magerun2 not supporting the php version.
If it's on a server you could upgrade it or add `FORCE_ONLINE_MAGERUN=true` to force the latest version of magerun to be used
